name = "Rigid"
uuid = "a02216df-6561-4a50-88cf-6852979b54d1"
authors = ["Hetao Z."]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
